### ISSUE TITLE
Unable to install wdio-image-comparison

### ISSUE THREAD

**Issue by Searcher865** [wswebcreation/webdriver-image-comparison#131]
**Environment (please complete the following information):**
 - Node.js version: [v18.14.0]
 - NPM version: [9.3.1]
 - Browser name and version: [Chrome 109.0.5414.119]
 - Platform name and version: [macOS Ventura 13.2 (22D49) macbook air m1]
 - Framework name and version: [webdriverIO 8]
 - Plugin name and version: [last]
 - webdriver-image-comparison version: [last]

**Describe the bug**
Unable to install wdio-image-comparison

**To Reproduce**
1) try npm i wdio-image-comparison 
or
wdio-image-comparison-service
or 
npm init wdio .   (select during initialization wdio-image-comparison-service)
[Include code or an example repository that can easily be set up]

**Expected behavior**
Successful installation

**Log**
```
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.3.1
2 info using node@v18.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/dmitrijsatov/Documents/automation/baucenter2/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/dmitrijsatov/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 5ms
17 timing npm:load:configload Completed in 5ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i wdio-image-comparison
21 verbose argv "i" "wdio-image-comparison"
22 timing npm:load:setTitle Completed in 5ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/dmitrijsatov/.npm/_logs/2023-02-04T13_46_13_459Z-
26 verbose logfile /Users/dmitrijsatov/.npm/_logs/2023-02-04T13_46_13_459Z-debug-0.log
27 timing npm:load:logFile Completed in 2ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 15ms
31 timing config:load:flatten Completed in 0ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 2 files
34 timing arborist:ctor Completed in 0ms
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 4ms
37 timing idealTree:userRequests Completed in 2ms
38 silly idealTree buildDeps
39 silly fetch manifest wdio-image-comparison@*
40 http fetch GET 404 https://registry.npmjs.org/wdio-image-comparison 1009ms (cache skip)
41 http fetch GET 404 https://registry.npmjs.org/wdio-image-comparison 1025ms (cache skip)
42 silly placeDep ROOT wdio-image-comparison@ OK for:  want: *
43 timing idealTree:#root Completed in 2045ms
44 timing idealTree:node_modules/wdio-image-comparison Completed in 0ms
45 timing idealTree:buildDeps Completed in 2046ms
46 timing idealTree:fixDepFlags Completed in 0ms
47 timing idealTree Completed in 2053ms
48 timing command:i Completed in 2056ms
49 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/wdio-image-comparison - Not found
49 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
49 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
49 verbose stack     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:85:19)
49 verbose stack     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:116:23)
49 verbose stack     at async [nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1059:19)
49 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
49 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:156:5)
49 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
50 verbose statusCode 404
51 verbose pkgid wdio-image-comparison@*
52 verbose cwd /Users/dmitrijsatov/Documents/automation/baucenter2
53 verbose Darwin 22.3.0
54 verbose node v18.14.0
55 verbose npm  v9.3.1
56 error code E404
57 error 404 Not Found - GET https://registry.npmjs.org/wdio-image-comparison - Not found
58 error 404
59 error 404  'wdio-image-comparison@*' is not in this registry.
60 error 404
60 error 404 Note that you can also install from a
61 error 404 tarball, folder, http url, or git url.
62 verbose exit 1
63 timing npm Completed in 2085ms
64 verbose unfinished npm timer reify 1675518373482
65 verbose unfinished npm timer reify:loadTrees 1675518373484
66 verbose code 1
67 error A complete log of this run can be found in:
67 error     /Users/dmitrijsatov/.npm/_logs/2023-02-04T13_46_13_459Z-debug-0.log
```

**Comment by wswebcreation** [comment]
Thanks for filing an issue:

1. this is not the correct project
2. you were installing the incorrect package, the name is not correct, please check https://github.com/wswebcreation/wdio-image-comparison-service#installation
